*import metadata;
proc import datafile='/folders/myfolders/testdata/Credit Card Marketing.csv'
dbms=csv out=data;run;
*delete duplicate id;
proc sort data=data out=data1 dupout=dup1 nodupkey;
by id;run;
*whether oversampling;
proc freq data=data1;
tables target_flag;run;
*positive:negative=1:1 -> 3:1;
*process for sampling;
proc sort data=data1;
by target_flag;run;
proc surveyselect data=data1  out=data2 samprate=(0.1,0.3);
strata target_flag;run;
*split train and test;
proc surveyselect data=data2 out=data3 outall seed=123 samprate=0.7;run;
data train test;set data3;
if selected=1 then output train;
else output test;
drop selected selectionprob samplingweight;run;
*define format;
proc format;
value $target 'N'=1
              'Y'=0;
run;
data train;
set train;
format target_flag target.;run;
data test;
set test;
format target_flag target.;run;
*corr counting;
proc corr data=train out=train_corr;run;